In [1]:
import requests
import pandas as pd

In [4]:
# Define the API details
ticker = "AAPL.US"  # Replace with your desired ticker
api_key = '672bae3e306da2.69377201'
api_token = api_key  # Replace with your API key
url = f"https://eodhd.com/api/fundamentals/{ticker}?api_token={api_token}&fmt=json"

# Fetch the data
response = requests.get(url)
data = response.json()
eps_data = data["Earnings"]["History"]

# Extract relevant information for each report
eps_records = [
    {
        "reportDate": record["reportDate"],
        "epsActual": record["epsActual"],
    }
    for record in eps_data.values()
]

# Convert to a DataFrame for easy handling
eps_df = pd.DataFrame(eps_records)

# Display the DataFrame sorted by report date (newest first)
eps_df = eps_df.sort_values(by="reportDate", ascending=False)
eps_df.head(10)

   reportDate  epsActual
0  2025-07-30        NaN
1  2025-04-30        NaN
2  2025-01-30        NaN
3  2024-10-31       1.64
4  2024-08-01       1.40
5  2024-05-02       1.53
6  2024-02-01       2.18
7  2023-11-02       1.46
8  2023-08-03       1.26
9  2023-05-04       1.52

In [8]:
tickers = ['AA',
 'AAL',
 'AAPL',
 'ABBV',
 'ABC',
 'ABK',
 'ABNB',
 'ABT',
 'ABX',
 'ACI',
 'ACN',
 'ACWI',
 'ADBE',
 'ADI',
 'ADM',
 'ADP',
 'ADSK',
 'AEM',
 'AET',
 'AFL',
 'AFRM',
 'AGN',
 'AGNC',
 'AGQ',
 'AGU',
 'AI',
 'AIG',
 'AKAM',
 'ALB',
 'ALGN',
 'ALL',
 'ALTR',
 'ALXN',
 'AMAT',
 'AMC',
 'AMD',
 'AMGN',
 'AMR',
 'AMT',
 'AMTD',
 'AMX',
 'AMZN',
 'ANET',
 'ANF',
 'ANR',
 'ANTM',
 'AON',
 'APA',
 'APC',
 'APD',
 'APOL',
 'ARKK',
 'ASML',
 'AT',
 'ATI',
 'ATVI',
 'AUY',
 'AVGO',
 'AXP',
 'AZN',
 'AZO',
 'BA',
 'BABA',
 'BAC',
 'BAX',
 'BBBY',
 'BBD',
 'BBT',
 'BBY',
 'BDX',
 'BEN',
 'BG',
 'BGU',
 'BHI',
 'BHP',
 'BIDU',
 'BIIB',
 'BIL',
 'BILI',
 'BJS',
 'BK',
 'BKNG',
 'BLK',
 'BMY',
 'BNI',
 'BNTX',
 'BP',
 'BRCM',
 'BRK.A',
 'BRK.B',
 'BSC',
 'BSX',
 'BTU',
 'BUD',
 'BX',
 'BXP',
 'C',
 'CAL',
 'CAT',
 'CB',
 'CBS',
 'CCI',
 'CCL',
 'CCU',
 'CDNS',
 'CELG',
 'CEPH',
 'CF',
 'CFC',
 'CHK',
 'CHTR',
 'CI',
 'CL',
 'CLF',
 'CLX',
 'CMCSA',
 'CMCSK',
 'CME',
 'CMG',
 'CMI',
 'CNC',
 'CNQ',
 'CNX',
 'COF',
 'COG',
 'COH',
 'COIN',
 'COP',
 'COST',
 'COUP',
 'COV',
 'CREE',
 'CRM',
 'CRWD',
 'CSCO',
 'CSX',
 'CTL',
 'CTSH',
 'CTX',
 'CTXS',
 'CVNA',
 'CVS',
 'CVX',
 'CXO',
 'D',
 'DAL',
 'DASH',
 'DD',
 'DDD',
 'DDM',
 'DDOG',
 'DE',
 'DELL',
 'DFS',
 'DG',
 'DHR',
 'DIA',
 'DIG',
 'DIS',
 'DLTR',
 'DNA',
 'DO',
 'DOCU',
 'DOW',
 'DRYS',
 'DTV',
 'DUG',
 'DUK',
 'DUST',
 'DVN',
 'DXCM',
 'DXD',
 'DXJ',
 'EA',
 'EBAY',
 'ECA',
 'EEM',
 'EL',
 'EMB',
 'EMC',
 'EMR',
 'ENDP',
 'ENPH',
 'EOG',
 'EP',
 'EQIX',
 'ERTS',
 'ERX',
 'ESRX',
 'ESV',
 'ETN',
 'ETR',
 'ETSY',
 'EW',
 'EWJ',
 'EWW',
 'EWY',
 'EWZ',
 'EXC',
 'EXPE',
 'EZU',
 'F',
 'FAS',
 'FAZ',
 'FB',
 'FCX',
 'FDC',
 'FDX',
 'FEYE',
 'FFIV',
 'FIS',
 'FISV',
 'FITB',
 'FLR',
 'FNM',
 'FOXA',
 'FRE',
 'FSLR',
 'FUTU',
 'FWLT',
 'FXE',
 'FXI',
 'GD',
 'GDX',
 'GDXJ',
 'GE',
 'GENZ',
 'GG',
 'GILD',
 'GIS',
 'GLW',
 'GM',
 'GMCR',
 'GME',
 'GOLD',
 'GOOG',
 'GOOGL',
 'GPN',
 'GPS',
 'GRMN',
 'GS',
 'GSF',
 'HAL',
 'HANS',
 'HCA',
 'HD',
 'HEDJ',
 'HES',
 'HIG',
 'HLF',
 'HON',
 'HOT',
 'HPE',
 'HPQ',
 'HTZ',
 'HUM',
 'IAU',
 'IBB',
 'IBM',
 'ICE',
 'IEFA',
 'IEMG',
 'IGV',
 'IJH',
 'IJR',
 'ILMN',
 'INCY',
 'INTC',
 'INTU',
 'IP',
 'ISRG',
 'ITUB',
 'ITW',
 'IVV',
 'IWB',
 'IWD',
 'IWF',
 'IWM',
 'IWN',
 'IWO',
 'IYF',
 'IYR',
 'JCI',
 'JCP',
 'JD',
 'JNJ',
 'JNK',
 'JNPR',
 'JNUG',
 'JPM',
 'JWN',
 'KBE',
 'KBH',
 'KFT',
 'KHC',
 'KLAC',
 'KMB',
 'KMI',
 'KO',
 'KORS',
 'KR',
 'KRE',
 'KSS',
 'KWEB',
 'LBTYA',
 'LEN',
 'LIN',
 'LLTC',
 'LLY',
 'LM',
 'LMT',
 'LNG',
 'LNKD',
 'LOW',
 'LRCX',
 'LULU',
 'LUV',
 'LVLT',
 'LVS',
 'LYB',
 'M',
 'MA',
 'MAR',
 'MARA',
 'MBI',
 'MCD',
 'MCHI',
 'MCHP',
 'MCK',
 'MCO',
 'MDB',
 'MDLZ',
 'MDT',
 'MDY',
 'MEE',
 'MELI',
 'MER',
 'MET',
 'MGM',
 'MHS',
 'MMM',
 'MO',
 'MON',
 'MOS',
 'MOT',
 'MPC',
 'MRK',
 'MRNA',
 'MRO',
 'MRVL',
 'MS',
 'MSFT',
 'MSTR',
 'MT',
 'MTCH',
 'MU',
 'MUB',
 'MXIM',
 'MYL',
 'NBR',
 'NCC',
 'NCLH',
 'NE',
 'NEE',
 'NEM',
 'NET',
 'NFLX',
 'NIHD',
 'NIO',
 'NKE',
 'NLY',
 'NOC',
 'NOK',
 'NOV',
 'NOW',
 'NSC',
 'NSM',
 'NTAP',
 'NTES',
 'NTRS',
 'NUE',
 'NUGT',
 'NVAX',
 'NVDA',
 'NVS',
 'NWSA',
 'NXPI',
 'NYX',
 'OIH',
 'OKTA',
 'ON',
 'ORCL',
 'ORLY',
 'OXY',
 'P',
 'PANW',
 'PBR',
 'PBR.A',
 'PCLN',
 'PCP',
 'PCU',
 'PD',
 'PDD',
 'PENN',
 'PEP',
 'PFE',
 'PG',
 'PGR',
 'PHM',
 'PINS',
 'PLD',
 'PLTR',
 'PLUG',
 'PM',
 'PNC',
 'POT',
 'PRGO',
 'PRU',
 'PSA',
 'PSQ',
 'PSX',
 'PTON',
 'PX',
 'PXD',
 'PYPL',
 'Q',
 'QCOM',
 'QID',
 'QIHU',
 'QLD',
 'QQQ',
 'QQQQ',
 'RAI',
 'RBLX',
 'RCL',
 'RDS.A',
 'REGN',
 'RF',
 'RHT',
 'RIG',
 'RIMM',
 'RIO',
 'RIOT',
 'RIVN',
 'RKH',
 'RMBS',
 'RNG',
 'ROKU',
 'RSP',
 'RSX',
 'RTH',
 'RTN',
 'RTX',
 'S',
 'SBUX',
 'SCHW',
 'SDS',
 'SE',
 'SEPR',
 'SGP',
 'SH',
 'SHLD',
 'SHOP',
 'SHPG',
 'SHW',
 'SHY',
 'SII',
 'SINA',
 'SIRI',
 'SKF',
 'SLB',
 'SLM',
 'SLW',
 'SMCI',
 'SMH',
 'SNAP',
 'SNDK',
 'SNOW',
 'SNPS',
 'SO',
 'SOXL',
 'SOXS',
 'SOXX',
 'SPCE',
 'SPG',
 'SPGI',
 'SPLS',
 'SPOT',
 'SPXL',
 'SPXS',
 'SPXU',
 'SPY',
 'SQ',
 'SQQQ',
 'SRS',
 'SSO',
 'STI',
 'STJ',
 'STP',
 'STT',
 'STX',
 'STZ',
 'SU',
 'SUN',
 'SUNE',
 'SUNW',
 'SVXY',
 'SWKS',
 'SWN',
 'SYF',
 'SYK',
 'SYMC',
 'T',
 'TBT',
 'TCK',
 'TDOC',
 'TEAM',
 'TEVA',
 'TFC',
 'TGT',
 'TIE',
 'TIP',
 'TJX',
 'TLRY',
 'TMO',
 'TMUS',
 'TNA',
 'TOL',
 'TOT',
 'TQQQ',
 'TRV',
 'TSLA',
 'TSM',
 'TSN',
 'TSO',
 'TTD',
 'TTWO',
 'TVIX',
 'TWC',
 'TWLO',
 'TWM',
 'TWTR',
 'TWX',
 'TXN',
 'TYC',
 'TZA',
 'U',
 'UA',
 'UAL',
 'UBER',
 'UGAZ',
 'ULTA',
 'UNG',
 'UNH',
 'UNP',
 'UPRO',
 'UPS',
 'UPST',
 'USB',
 'USMV',
 'USO',
 'UTX',
 'UVXY',
 'UYG',
 'V',
 'VALE',
 'VALE.P',
 'VCIT',
 'VCSH',
 'VEA',
 'VGK',
 'VIAB',
 'VIAC',
 'VLO',
 'VMW',
 'VNO',
 'VOD',
 'VOO',
 'VRTX',
 'VRX',
 'VTI',
 'VTV',
 'VWO',
 'VXX',
 'VZ',
 'W',
 'WAG',
 'WB',
 'WBA',
 'WDAY',
 'WDC',
 'WFC',
 'WFM',
 'WFMI',
 'WFR',
 'WFT',
 'WLL',
 'WLP',
 'WLT',
 'WM',
 'WMB',
 'WMT',
 'WY',
 'WYE',
 'WYNN',
 'X',
 'XBI',
 'XHB',
 'XIV',
 'XLB',
 'XLC',
 'XLE',
 'XLF',
 'XLI',
 'XLK',
 'XLNX',
 'XLP',
 'XLU',
 'XLV',
 'XLY',
 'XME',
 'XOM',
 'XOP',
 'XRT',
 'XTO',
 'YELP',
 'YHOO',
 'YUM',
 'Z',
 'ZM',
 'ZS',
 'ZTS',"GOLD", "NTR", "TFC", "BKR", "AVGO", "BRK-A", "BRK-B", "PARA",
        "CMCSA", "CTRA", "TPR", "MDT", "WOLF", "EA", "VAL","MNST", "KHC", "VTRS", "ICE", "PBR", "BKNG", "NTR", "SHEL", "BB",
        "WPM",  "TECK", "TTE", "RTX", "VALE","WBA"]

In [9]:
import requests
import pickle
import pandas as pd

# Define the API details
api_key = '672bae3e306da2.69377201'
api_token = api_key  # Replace with your API key

# List of stock names to fetch data for
stocks = tickers

# Dictionary to store EPS data for each stock
eps_data_dict = {}

for stock in stocks:
    ticker = f"{stock}.US"  # Add '.US' to the stock name for API
    url = f"https://eodhd.com/api/fundamentals/{ticker}?api_token={api_token}&fmt=json"
    try:
        response = requests.get(url)
        data = response.json()
        
        # Extract EPS history
        if "Earnings" in data and "History" in data["Earnings"]:
            eps_data = data["Earnings"]["History"]
            eps_records = [
                {
                    "reportDate": record["reportDate"],
                    "epsActual": record["epsActual"],
                }
                for record in eps_data.values()
            ]
            
            # Convert to a DataFrame and store it
            eps_df = pd.DataFrame(eps_records).sort_values(by="reportDate", ascending=False)
            eps_data_dict[stock] = eps_df
    except Exception as e:
        print(f"Failed to fetch data for {stock}: {e}")

# Save the EPS data dictionary to a pickle file
with open('eps_data.pkl', 'wb') as file:
    pickle.dump(eps_data_dict, file)

# Confirm the saved data
eps_data_dict.keys()

Failed to fetch data for ABK: 'reportDate'
Failed to fetch data for ANR: 'reportDate'
Failed to fetch data for APOL: 'reportDate'
Failed to fetch data for BGU: Expecting value: line 1 column 1 (char 0)
Failed to fetch data for BJS: 'reportDate'
Failed to fetch data for BNI: 'reportDate'
Failed to fetch data for BRCM: 'reportDate'
Failed to fetch data for BRK.A: Expecting value: line 1 column 1 (char 0)
Failed to fetch data for BRK.B: Expecting value: line 1 column 1 (char 0)
Failed to fetch data for CEPH: 'reportDate'
Failed to fetch data for CFC: 'reportDate'
Failed to fetch data for CMCSK: 'reportDate'
Failed to fetch data for COV: 'reportDate'
Failed to fetch data for CTX: 'reportDate'
Failed to fetch data for DRYS: 'reportDate'
Failed to fetch data for DTV: 'reportDate'
Failed to fetch data for ERTS: 'reportDate'
Failed to fetch data for FNM: 'reportDate'
Failed to fetch data for FRE: 'reportDate'
Failed to fetch data for FWLT: 'reportDate'
Failed to fetch data for GENZ: 'reportDate'
Failed to fetch data for GMCR: 'reportDate'
Failed to fetch data for GSF: 'reportDate'
Failed to fetch data for HANS: Expecting value: line 1 column 1 (char 0)
Failed to fetch data for KFT: 'reportDate'
Failed to fetch data for LLTC: 'reportDate'
Failed to fetch data for LNKD: 'reportDate'
Failed to fetch data for MEE: 'reportDate'
Failed to fetch data for MER: 'reportDate'
Failed to fetch data for MHS: 'reportDate'
Failed to fetch data for MOT: 'reportDate'
Failed to fetch data for NCC: 'reportDate'
Failed to fetch data for NYX: 'reportDate'
Failed to fetch data for PBR.A: Expecting value: line 1 column 1 (char 0)
Failed to fetch data for PCP: 'reportDate'
Failed to fetch data for PCU: Expecting value: line 1 column 1 (char 0)
Failed to fetch data for QIHU: 'reportDate'
Failed to fetch data for QQQQ: Expecting value: line 1 column 1 (char 0)
Failed to fetch data for RDS.A: Expecting value: line 1 column 1 (char 0)
Failed to fetch data for RHT: 'reportDate'
Failed to fetch data for RIMM: Expecting value: line 1 column 1 (char 0)
Failed to fetch data for SEPR: 'reportDate'
Failed to fetch data for SGP: 'reportDate'
Failed to fetch data for SNDK: 'reportDate'
Failed to fetch data for SPLS: 'reportDate'
Failed to fetch data for STJ: 'reportDate'
Failed to fetch data for STP: Expecting value: line 1 column 1 (char 0)
Failed to fetch data for SUNE: 'reportDate'
Failed to fetch data for SYMC: 'reportDate'
Failed to fetch data for TCK: 'reportDate'
Failed to fetch data for TIE: 'reportDate'
Failed to fetch data for TOT: Expecting value: line 1 column 1 (char 0)
Failed to fetch data for TWC: 'reportDate'
Failed to fetch data for TYC: 'reportDate'
Failed to fetch data for VALE.P: Expecting value: line 1 column 1 (char 0)
Failed to fetch data for WAG: 'reportDate'
Failed to fetch data for WFMI: Expecting value: line 1 column 1 (char 0)
Failed to fetch data for WFR: 'reportDate'
Failed to fetch data for WLP: 'reportDate'
Failed to fetch data for WLT: 'reportDate'
Failed to fetch data for WYE: 'reportDate'
Failed to fetch data for XTO: 'reportDate'

dict_keys(['AA', 'AAL', 'AAPL', 'ABBV', 'ABC', 'ABNB', 'ABT', 'ABX', 'ACI', 'ACN', 'ADBE', 'ADI', 'ADM', 'ADP', 'ADSK', 'AEM', 'AET', 'AFL', 'AFRM', 'AGN', 'AGNC', 'AGU', 'AI', 'AIG', 'AKAM', 'ALB', 'ALGN', 'ALL', 'ALTR', 'ALXN', 'AMAT', 'AMC', 'AMD', 'AMGN', 'AMR', 'AMT', 'AMTD', 'AMX', 'AMZN', 'ANET', 'ANF', 'ANTM', 'AON', 'APA', 'APC', 'APD', 'ASML', 'AT', 'ATI', 'ATVI', 'AUY', 'AVGO', 'AXP', 'AZN', 'AZO', 'BA', 'BABA', 'BAC', 'BAX', 'BBBY', 'BBD', 'BBT', 'BBY', 'BDX', 'BEN', 'BG', 'BHI', 'BHP', 'BIDU', 'BIIB', 'BILI', 'BK', 'BKNG', 'BLK', 'BMY', 'BNTX', 'BP', 'BSX', 'BTU', 'BUD', 'BX', 'BXP', 'C', 'CAL', 'CAT', 'CB', 'CBS', 'CCI', 'CCL', 'CCU', 'CDNS', 'CELG', 'CF', 'CHK', 'CHTR', 'CI', 'CL', 'CLF', 'CLX', 'CMCSA', 'CME', 'CMG', 'CMI', 'CNC', 'CNQ', 'CNX', 'COF', 'COG', 'COH', 'COIN', 'COP', 'COST', 'COUP', 'CREE', 'CRM', 'CRWD', 'CSCO', 'CSX', 'CTL', 'CTSH', 'CTXS', 'CVNA', 'CVS', 'CVX', 'CXO', 'D', 'DAL', 'DASH', 'DD', 'DDD', 'DDOG', 'DE', 'DELL', 'DFS', 'DG', 'DHR', 'DIS', 'DLTR', 'DNA', 'DO', 'DOCU', 'DOW', 'DUK', 'DVN', 'DXCM', 'EA', 'EBAY', 'ECA', 'EL', 'EMR', 'ENDP', 'ENPH', 'EOG', 'EP', 'EQIX', 'ESRX', 'ESV', 'ETN', 'ETR', 'ETSY', 'EW', 'EXC', 'EXPE', 'F', 'FB', 'FCX', 'FDC', 'FDX', 'FEYE', 'FFIV', 'FIS', 'FISV', 'FITB', 'FLR', 'FOXA', 'FSLR', 'FUTU', 'GD', 'GE', 'GG', 'GILD', 'GIS', 'GLW', 'GM', 'GME', 'GOLD', 'GOOG', 'GOOGL', 'GPN', 'GPS', 'GRMN', 'GS', 'HAL', 'HCA', 'HD', 'HES', 'HIG', 'HLF', 'HON', 'HOT', 'HPE', 'HPQ', 'HTZ', 'HUM', 'IBM', 'ICE', 'ILMN', 'INCY', 'INTC', 'INTU', 'IP', 'ISRG', 'ITUB', 'ITW', 'JCI', 'JCP', 'JD', 'JNJ', 'JNPR', 'JPM', 'JWN', 'KBH', 'KHC', 'KLAC', 'KMB', 'KMI', 'KO', 'KORS', 'KR', 'KSS', 'LBTYA', 'LEN', 'LIN', 'LLY', 'LM', 'LMT', 'LNG', 'LOW', 'LRCX', 'LULU', 'LUV', 'LVLT', 'LVS', 'LYB', 'M', 'MA', 'MAR', 'MARA', 'MBI', 'MCD', 'MCHP', 'MCK', 'MCO', 'MDB', 'MDLZ', 'MDT', 'MELI', 'MET', 'MGM', 'MMM', 'MO', 'MON', 'MOS', 'MPC', 'MRK', 'MRNA', 'MRO', 'MRVL', 'MS', 'MSFT', 'MSTR', 'MT', 'MTCH', 'MU', 'MXIM', 'MYL', 'NBR', 'NCLH', 'NE', 'NEE', 'NEM', 'NET', 'NFLX', 'NIHD', 'NIO', 'NKE', 'NLY', 'NOC', 'NOK', 'NOV', 'NOW', 'NSC', 'NSM', 'NTAP', 'NTES', 'NTRS', 'NUE', 'NVAX', 'NVDA', 'NVS', 'NWSA', 'NXPI', 'OKTA', 'ON', 'ORCL', 'ORLY', 'OXY', 'P', 'PANW', 'PBR', 'PCLN', 'PD', 'PDD', 'PENN', 'PEP', 'PFE', 'PG', 'PGR', 'PHM', 'PINS', 'PLD', 'PLTR', 'PLUG', 'PM', 'PNC', 'POT', 'PRGO', 'PRU', 'PSA', 'PSX', 'PTON', 'PX', 'PXD', 'PYPL', 'Q', 'QCOM', 'RAI', 'RBLX', 'RCL', 'REGN', 'RF', 'RIG', 'RIO', 'RIOT', 'RIVN', 'RMBS', 'RNG', 'ROKU', 'RTN', 'RTX', 'S', 'SBUX', 'SCHW', 'SE', 'SHOP', 'SHPG', 'SHW', 'SII', 'SINA', 'SIRI', 'SLB', 'SLM', 'SLW', 'SMCI', 'SNAP', 'SNOW', 'SNPS', 'SO', 'SPCE', 'SPG', 'SPGI', 'SPOT', 'SQ', 'STI', 'STT', 'STX', 'STZ', 'SU', 'SUN', 'SUNW', 'SWKS', 'SWN', 'SYF', 'SYK', 'T', 'TDOC', 'TEAM', 'TEVA', 'TFC', 'TGT', 'TJX', 'TLRY', 'TMO', 'TMUS', 'TOL', 'TRV', 'TSLA', 'TSM', 'TSN', 'TSO', 'TTD', 'TTWO', 'TWLO', 'TWTR', 'TWX', 'TXN', 'U', 'UA', 'UAL', 'UBER', 'ULTA', 'UNH', 'UNP', 'UPS', 'UPST', 'USB', 'UTX', 'V', 'VALE', 'VIAB', 'VIAC', 'VLO', 'VMW', 'VNO', 'VOD', 'VRTX', 'VRX', 'VZ', 'W', 'WB', 'WBA', 'WDAY', 'WDC', 'WFC', 'WFM', 'WFT', 'WLL', 'WM', 'WMB', 'WMT', 'WY', 'WYNN', 'X', 'XLNX', 'XOM', 'YELP', 'YHOO', 'YUM', 'Z', 'ZM', 'ZS', 'ZTS', 'NTR', 'BKR', 'BRK-A', 'BRK-B', 'PARA', 'CTRA', 'TPR', 'WOLF', 'VAL', 'MNST', 'VTRS', 'SHEL', 'BB', 'WPM', 'TECK', 'TTE'])

In [11]:
eps_data_dict['GOLD']

     reportDate  epsActual
0    2025-04-29        NaN
1    2025-02-12        NaN
2    2024-10-31       0.30
3    2024-08-12       0.32
4    2024-05-01       0.19
..          ...        ...
115  1996-07-18       0.19
116  1996-04-22       0.20
117  1996-01-30       0.22
118  1995-10-18       0.19
119  1995-07-17       0.21

[120 rows x 2 columns]

In [7]:
eps_data_dict['AAPL']

     reportDate  epsActual
0    2025-07-30        NaN
1    2025-04-30        NaN
2    2025-01-30        NaN
3    2024-10-31     1.6400
4    2024-08-01     1.4000
..          ...        ...
122  1995-01-19     0.0500
123  1994-10-17     0.0300
124  1994-06-30     0.0104
125  1994-03-31     0.0104
126  1993-12-31     0.0031

[127 rows x 2 columns]